version: '3.8'

services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env

  frontend:
    build:
      context: ./front-end-nextjs
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"